# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Refrigerator', '0004_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='list_id',
        ),
    ]
