# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Refrigerator', '0009_auto_20170512_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Info',
        ),
    ]
